### ISSUE TITLE
Light Color Seems to be having issues

### ISSUE THREAD

**Issue by justinthejaguar** [kandashi/Active-Token-Lighting#148] opened 2023-09-14 03:16 UTC
**Describe the bug**
When I enter
ATL.light.color I am getting an error with my entries. Tried different cases just in case it was case sensitive.

**To Reproduce**
1. Add ATL Light Color to an on equip item
2. Equip Item
3. See error

**Expected behavior**
There should be coloration.

**Screenshots**
![Screenshot 2023-09-13 at 11 07 17 PM](https://github.com/kandashi/Active-Token-Lighting/assets/38022481/9045480c-ea92-4fa4-be9d-0f5e9a34598d)

**Environment:**
 - OS: Node running on Rpi playing on Mac
 - Browser chrome
 - Foundry Version 11.308
 - Module Version 0.7.0
 - All Modules Disabled: Yes

**Comment by justinthejaguar** [comment] 2023-09-14 03:17
Attempted strings:
#00FFFF
#00ffff
#ffffff

**Comment by kaelad02** [comment] 2023-09-14 03:21
What change mode are you using in the active effect?

I tried an active effect like this and it worked as expected:
![image](https://github.com/kandashi/Active-Token-Lighting/assets/19502084/90e2636c-1620-4843-a38d-dd560c90aac1)

**Comment by kaelad02** [comment] 2023-09-14 03:25
Hmm, I tried it with a couple other change modes and still didn't reproduce. To verify, what game system are you using (e.g. dnd5e)?

**Comment by justinthejaguar** [comment] 2023-09-14 04:07
I used add. I bet that was the issue. I will do override in the morning.

**Comment by kaelad02** [comment] 2023-09-14 04:09
I can reproduce it using Add. I see the same error. Switching it to override will do the trick.

**Comment by dineshm72** [comment] 2023-10-14 04:04
I am having the same problem as above.  Using ATL.light.color on an item I am triggering does not include the color.

<img width="1425" alt="image" src="https://github.com/kandashi/Active-Token-Lighting/assets/2231877/9661dc69-6589-41be-8b2f-be948b8841c8">

I also note that there doesn't seem to be an option for color intensity listed.  Is alpha the option that maps to color intensity?  I don't see any place where you can set an "alpha" for light on the token options.  In any case, setting ATL.light.alpha also does not seem to do anything that I can tell.

**Comment by dineshm72** [comment] 2023-10-14 04:32
I think I figured out my issue.  The effect was being toggled off/on, so none of my later edits to add the color were getting incorporated.

**Comment by dineshm72** [comment] 2023-10-14 04:33
Can also confirm that light.alpha = light intensity setting.

**Comment by kaelad02** [comment] 2023-10-14 13:10
I updated the descriptions for some of the keys on the wiki. Mainly putting the label you see in the token config there (e.g. `ATL.light.alpha` => "Light Color Intensity")

**Comment by kaelad02** [comment] 2023-10-14 13:11
Closing since the original issue was fixed by using Override instead of Add for the color.

**Closed by kaelad02** 2023-10-14 13:11 UTC
Labels: bug
